version: "3"

services:
  web:
    image: php:8.2.8-apache
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - "./html:/var/www/html"
      - "./docker/php/php.ini:/usr/local/etc/php/php.ini"
    environment:
      - "TZ=Asia/Tokyo"
    working_dir: "/var/www/html"
